version: "3.4"
services:
  app:
    image: registry.gitlab.bzcom.vn/bzc1/bzc-fe:latest
    volumes:
      - bzc-fe:/upload
    ports:
      - "5782:80"
    restart: unless-stopped
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5
      test: []
volumes:
  bzc-fe:
