image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.16-dind

before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest


test:
  stage: test
  script:
    - echo "Run test tool"



deploy-staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update && apk add openssh-client bash
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - ssh-keyscan -H -p $PORT $SSH_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - >
      ssh -T -p $PORT $SSH_USER@$SSH_SERVER_IP
      "
      echo $PASSWORD | sudo -S docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
      cd ${PATH_TO_PROJECT};
      echo $PASSWORD | sudo -S docker compose down;
      echo $PASSWORD | sudo -S docker pull ${CI_REGISTRY_IMAGE}:latest;
      echo $PASSWORD | sudo -S docker compose up -d;
      echo $PASSWORD | sudo -S docker image prune -f;
      "
  only:
    refs:
      - staging
  environment: staging
