version: "3.4"
services:
    app:
        image: registry.gitlab.bzcom.vn/tms/tms-fe/tms-fe:latest
        ports:
            - "3000:80"
        restart: unless-stopped
        healthcheck:
            interval: 30s
            timeout: 10s
            retries: 5
            test: []